# Setup and Load Data

In [96]:
import numpy as np
import pandas as pd

In [97]:
def read_n_create_index(cityname):
    data = pd.read_csv("rent_listings_"+cityname+".csv")
    data['city_id'] = cityname + '_' +  data.index.astype(str)
    data.set_index('city_id', inplace=True)
    print("Size of the data:", data.shape)
    display(data.head())
    return data

In [98]:
lagos_data = read_n_create_index('lagos')

Size of the data: (5000, 6)

,neighborhood,price,beds,baths,toilets,extra
city_id,,,,,,
lagos_0,OLALEYE Estate Alaka Iponri Surulere Lagos,"₦ 2,500,000",3 beds,4 baths,4 Toilets,Brand new service 3 bedroom flat all rooms ens...
lagos_1,"Off Kudirat Abiola way, Julie EstateOregun Ike...","₦ 2,500,000",3 beds,3 baths,4 Toilets,The property is a 3 Bedrooms Upscale FLAT all ...
lagos_2,-Old Ikoyi Ikoyi Lagos,"$ 40,000",3 beds,3 baths,4 Toilets,Serviced Newly Built3 bedroom Flat / Apartment...
lagos_3,...Lekki Phase 1 Lekki Lagos,"₦ 800,000",1 beds,1 baths,1 Toilets,"For more information, Pricing, and Private Vie..."
lagos_4,Lekki Phase 1 Lekki Lagos,"₦ 1,200,000",1 beds,1 baths,1 Toilets,"For more information, Pricing, and Private Vie..."

In [99]:
abuja_data = read_n_create_index('abuja')

Size of the data: (739, 6)

,neighborhood,price,beds,baths,toilets,extra
city_id,,,,,,
abuja_0,Sam najuma estate GaladimawaLokogoma Abuja,"₦ 1,300,000",3 beds,3 baths,4 Toilets,Sharp 2nd floor 3 bedroom apartment @ Dr Sam n...
abuja_1,DawakiGwarinpa Abuja,"₦ 1,500,000",3 beds,3 baths,4 Toilets,Newly BuiltIt's newly built and never been occ...
abuja_2,Gaduwa Abuja,"₦ 1,500,000",3 beds,3 baths,4 Toilets,"3bedroom blocks of flat in Gaduwa District, gr..."
abuja_3,Maitama Abuja,"₦ 2,500,000",2 beds,2 baths,4 Toilets,ServicedA Serviced 2 bedroom flat in #maitama ...
abuja_4,In an estate behind games village Garki 1 Abuja,"₦ 1,500,000",2 beds,2 baths,3 Toilets,"2 Bedroom Flat With CCTV, Constant Water Suppl..."

In [100]:
ogun_data = read_n_create_index('ogun')

Size of the data: (188, 6)

,neighborhood,price,beds,baths,toilets,extra
city_id,,,,,,
ogun_0,ShimawaMowe Obafemi Owode Ogun,"₦ 260,000",3 beds,1 baths,2 Toilets,"Newly BuiltA newly built 1 bed, 2 beds and 3 b..."
ogun_1,Adigbe Abeokuta Ogun,"₦ 300,000",2 beds,3 baths,3 Toilets,2 bedroom Shared Apartment Flat / Apartment fo...
ogun_2,Private EstateMagboro Obafemi Owode Ogun,"₦ 250,000",1 beds,1 baths,2 Toilets,Spacious Rooms Ample Parking Space Kitchen Cab...
ogun_3,MagboroMagboro Obafemi Owode Ogun,"₦ 350,000",2 beds,2 baths,2 Toilets,24-hours Security Spacious Rooms Ample Parking...
ogun_4,Private EstateArepo Ogun,"₦ 450,000",2 beds,2 baths,3 Toilets,24-hours Security Spacious Rooms Ample Parking...

In [101]:
ibadan_data = read_n_create_index('oyo')

Size of the data: (512, 6)

,neighborhood,price,beds,baths,toilets,extra
city_id,,,,,,
oyo_0,Iyaganku GRA quarters IbadanIyanganku Ibadan Oyo,"₦ 1,000,000",3 beds,3 baths,3 Toilets,*To let Three bedroom flat en suit is availabl...
oyo_1,Behind DSS ile tuntun nihort Jericho ibadanIdi...,"₦ 450,000",3 beds,3 baths,3 Toilets,"*To let* 4 flat of 3 bedroom with 3 toilets, b..."
oyo_2,Yidi apete junction ibadan Ibadan Polytechnic...,"₦ 126,000",1 beds,1 baths,1 Toilets,Serviced Newly BuiltA room selfcon at Yidi ape...
oyo_3,"Adeoyo GRA, off ring road, ibadan Ring Rd Ibad...","₦ 750,000",3 beds,3 baths,4 Toilets,Newly BuiltFinely finished 3 bedroom Apartment...
oyo_4,"Opposition nnpc filling station, akala express...","₦ 600,000",3 beds,3 baths,4 Toilets,Newly BuiltBrand new 3 bedroom Apartment for r...

In [102]:
ph_data = read_n_create_index('rivers')

Size of the data: (105, 6)

,neighborhood,price,beds,baths,toilets,extra
city_id,,,,,,
rivers_0,GRA phase 3 tombia extensionNew Gra Port Harco...,"₦ 1,500,000",2 beds,2 baths,2 Toilets,Newly Built2no newly built 2bed room flats in ...
rivers_1,Ada George Port Harcourt Rivers,"₦ 500,000",2 beds,2 baths,2 Toilets,Furnished Newly BuiltA VIRGIN TWO BEDROOM FLAT...
rivers_2,odili roadTrans Amadi Port Harcourt Rivers,"₦ 550,000",1 beds,1 baths,2 Toilets,One bedroom for [email protected] #550k odili ...
rivers_3,Trans Amadi Port Harcourt Rivers,"₦ 650,000",beds,baths,Toilets,Decent King Size 2 Bedroom Flat For Rent In Wo...
rivers_4,...Trans Amadi Port Harcourt Rivers,"₦ 800,000",0 beds,0 baths,0 Toilets,King Size 2 Bedroom For Rent In Woji Port Har...

## Data Lookup and Cleaning

In [103]:
data = pd.concat([lagos_data, abuja_data, ibadan_data, ogun_data, ph_data])
print("Size of the data:", data.shape)

data.head()

Size of the data: (6544, 6)

,neighborhood,price,beds,baths,toilets,extra
city_id,,,,,,
lagos_0,OLALEYE Estate Alaka Iponri Surulere Lagos,"₦ 2,500,000",3 beds,4 baths,4 Toilets,Brand new service 3 bedroom flat all rooms ens...
lagos_1,"Off Kudirat Abiola way, Julie EstateOregun Ike...","₦ 2,500,000",3 beds,3 baths,4 Toilets,The property is a 3 Bedrooms Upscale FLAT all ...
lagos_2,-Old Ikoyi Ikoyi Lagos,"$ 40,000",3 beds,3 baths,4 Toilets,Serviced Newly Built3 bedroom Flat / Apartment...
lagos_3,...Lekki Phase 1 Lekki Lagos,"₦ 800,000",1 beds,1 baths,1 Toilets,"For more information, Pricing, and Private Vie..."
lagos_4,Lekki Phase 1 Lekki Lagos,"₦ 1,200,000",1 beds,1 baths,1 Toilets,"For more information, Pricing, and Private Vie..."

### Cleaning Price;

In [104]:
data.price.unique()

array(['₦ 2,500,000', '$ 40,000', '₦ 800,000', '₦ 1,200,000',
       '₦ 1,000,000', '₦ 350,000', '₦ 550,000', '₦ 700,000',
       '₦ 2,000,000', '₦ 500,000', '₦ 400,000', '₦ 600,000', '₦ 300,000',
       '₦ 900,000', '₦ 1,500,000', '₦ 1,800,000', '₦ 850,000',
       '₦ 170,000', '₦ 1,600,000', '₦ 650,000', '₦ 750,000',
       '₦ 1,300,000', '₦ 1,100,000', '₦ 2,300,000', '₦ 250,000',
       '₦ 1,400,000', '₦ 450,000', '₦ 200,000', '₦ 120,000',
       '₦ 1,700,000', '₦ 950,000', '₦ 55,000', '₦ 130,000', '₦ 1,900,000',
       '₦ 65,000', '₦ 1,850,000', '₦ 150,000', '₦ 1,650,000', '₦ 470,000',
       '₦ 1,350,000', '₦ 270,000', '₦ 35,000', '$ 25,000', '$ 65,000',
       '₦ 2,200,000', '$ 100,000', '₦ 2,250,000', '$ 80,000', '$ 28,000',
       '₦ 70,000', '$ 50,000', '₦ 2,100,000', '₦ 840,000', '$ 70,000',
       '₦ 210,000', '₦ 216,000', '₦ 250', '₦ 84,000', '₦ 160,000',
       '₦ 1,025,000', '₦ 230,000', '₦ 280,000', '₦ 480,000', '₦ 430,000',
       '₦ 220,000', '₦ 2,400,000', '₦ 330,000', '₦ 180,000', '₦ 530,000',
       '₦ 10,000', '₦ 380,000', '₦ 420,000', '$ 75,000', '₦ 90,000',
       '₦ 110,000', '₦ 500', '₦ 1,150,000', '₦ 140,000', '₦ 1,250,000',
       '₦ 25,000', '₦ 100,000', '₦ 96,000', '₦ 40,000', '₦ 45,000',
       '₦ 460,000', '₦ 630,000', '₦ 72,000', '₦ 370,000', '₦ 6',
       '$ 90,000', '₦ 620,000', '₦ 1,200,009', '₦ 50,000', '₦ 320,000',
       '₦ 1,750,000', '$ 12,000', '₦ 60,000', '₦ 270', '₦ 150', '₦ 350',
       '₦ 190,000', '₦ 520,000', '₦ 1,380,000', '₦ 1,450,000', '₦ 600',
       '₦ 1', '₦ 750,009', '₦ 360,000', '₦ 4,000', '₦ 1,050,000',
       '₦ 830,000', '₦ 1,620,000', '₦ 2,700,000', '₦ 3,000,000',
       '₦ 3,500,000', '$ 35,000', '₦ 3,200,000', '₦ 2,800,000',
       '$ 18,000', '₦ 2,900,000', '₦ 4,000,000', '$ 68,000',
       '₦ 3,400,000', '₦ 2,850,000', '₦ 3,800,000', '₦ 2,600,000',
       '₦ 1,300', '$ 105,000', '₦ 2,750,000', '₦ 260,000', '₦ 3,300,000',
       '$ 45,000', '₦ 3,625,000', '₦ 297,000', '₦ 126,000', '₦ 240,000',
       '₦ 80,000', '₦ 478,000', '₦ 275,000', '₦ 820,000', '₦ 75,009',
       '₦ 153,000', '₦ 720,000'], dtype=object)

Some of the prices are in dollars! We'd probably drop those rows.

In [105]:
dollar_apartments = data[data.price.str.startswith('$')]
dollar_apartments

,neighborhood,price,beds,baths,toilets,extra
city_id,,,,,,
lagos_2,-Old Ikoyi Ikoyi Lagos,"$ 40,000",3 beds,3 baths,4 Toilets,Serviced Newly Built3 bedroom Flat / Apartment...
lagos_398,Victoria Island Lagos,"$ 25,000",3 beds,3 baths,4 Toilets,Modern spacious flat in Victoria Island Large ...
lagos_399,Victoria Island Lagos,"$ 65,000",3 beds,3 baths,4 Toilets,Luxury flats in Victoria Island 3 Bedroom apar...
lagos_404,Old Ikoyi Ikoyi Lagos,"$ 100,000",3 beds,3 baths,4 Toilets,Luxury waterfront apartment boasting private s...
lagos_408,Old Ikoyi Ikoyi Lagos,"$ 80,000",3 beds,3 baths,4 Toilets,Luxury waterfront apartment boasting private s...
lagos_412,Victoria Island Lagos,"$ 28,000",1 beds,1 baths,2 Toilets,1 bedroom mini flat Flat / Apartment for rent ...
lagos_433,Old Ikoyi Ikoyi Lagos,"$ 50,000",3 beds,3 baths,4 Toilets,Newly BuiltTastefully 3 bedroom flat with a Bq...
lagos_605,Ikoyi Lagos,"$ 70,000",3 beds,3 baths,4 Toilets,Serviced1t an exquisitely elegant development ...
lagos_1689,Ozumba MbadiweBonny Camp Victoria Island Lagos,"$ 75,000",3 beds,3 baths,4 Toilets,Furnished Serviced Newly BuiltDesigned by ECAD...
lagos_1874,-Eko Atlantic Victoria Island Lagos,"$ 50,000",3 beds,3 baths,4 Toilets,Serviced Newly Built3 bedroom apartment with S...
lagos_2268,Ligali Ayorinde Victoria Island Lagos,"$ 80,000",3 beds,4 baths,4 Toilets,Serviced Newly BuiltA mixed use development th...
lagos_2294,victoria island Victoria Island Victoria Islan...,"$ 65,000",3 beds,0 baths,0 Toilets,A tastefully and well finished 3 bedroom flat ...
lagos_2351,YOUNIS BASHORUNVictoria Island Extension Victo...,"$ 80,000",3 beds,3 baths,4 Toilets,Serviced Newly BuiltA mixed use development th...
lagos_2504,Banana Island Banana Island Ikoyi Lagos,"$ 90,000",3 beds,3 baths,4 Toilets,Furnished Serviced Newly Built3 bedroom Flat /...
lagos_2572,Adeola Odeku Kofo Abayomi Victoria Island Lagos,"$ 25,000",1 beds,2 baths,2 Toilets,Serviced Newly BuiltA spectacular new mixed us...
lagos_2581,Eko Atlantic Victoria Island Lagos,"$ 90,000",3 beds,3 baths,4 Toilets,FurnishedLocated in The Tallest residential bu...
lagos_2800,Banana IslandBanana Island Ikoyi Lagos,"$ 90,000",3 beds,3 baths,4 Toilets,Serviced Newly BuiltThe interior style is eleg...
lagos_3130,Kofo Abayomi Ahmadu Bello Way Victoria Island ...,"$ 12,000",1 beds,1 baths,1 Toilets,Furnished Serviced Newly BuiltA spectacular ne...
lagos_4082,Eko Atlantic Victoria Island Lagos,"$ 70,000",4 beds,4 baths,5 Toilets,Furnished Newly BuiltIf you're looking for an ...
lagos_4893,Banana IslandBanana Island Ikoyi Lagos,"$ 65,000",4 beds,4 baths,5 Toilets,Spacious 4 bedroom apartments in this prestigi...
lagos_4979,VIAkin Adesola Victoria Island Lagos,"$ 80,000",3 beds,3 baths,4 Toilets,3 bedroom smart luxury waterfront apartments f...
abuja_75,Oyi river streetMaitama Abuja,"$ 35,000",2 beds,2 baths,3 Toilets,Furnished Serviced Newly BuiltThis is a a resi...
abuja_81,Oyi river StreetMaitama Abuja,"$ 35,000",2 beds,2 baths,3 Toilets,Furnished ServicedGreetings. This is a a resid...
abuja_124,Osun crescentMaitama Abuja,"$ 18,000",3 beds,3 baths,4 Toilets,Serviced Newly BuiltDescription: A 3-bedroom l...
abuja_140,Maitama Maitama Abuja,"$ 68,000",3 beds,3 baths,4 Toilets,ServicedNewly vacated and extremely maintained...
abuja_143,MaitamaMaitama Abuja,"$ 25,000",3 beds,3 baths,4 Toilets,Serviced Newly BuiltLuxury and fully serviced ...
abuja_292,Sunrise HillsAsokoro Abuja,"$ 65,000",3 beds,3 baths,4 Toilets,Furnished Serviced Newly BuiltLuxurious apartm...
abuja_305,Sunrise HillsAsokoro Abuja,"$ 65,000",3 beds,3 baths,4 Toilets,Furnished Serviced Newly BuiltLuxurious apartm...
abuja_334,"Maitama, AbujaMaitama Abuja","$ 105,000",4 beds,4 baths,5 Toilets,"Serviced24hrs light clean water, 24 hrs securi..."
abuja_546,Asokoro Asokoro Abuja,"$ 45,000",3 beds,3 baths,4 Toilets,Furnished Serviced3 bedroom luxury serviced Ap...

They all seems to be located at either Lagos or Abuja.

In [106]:
data.drop(dollar_apartments.index, inplace=True)

data.price.unique()

array(['₦ 2,500,000', '₦ 800,000', '₦ 1,200,000', '₦ 1,000,000',
       '₦ 350,000', '₦ 550,000', '₦ 700,000', '₦ 2,000,000', '₦ 500,000',
       '₦ 400,000', '₦ 600,000', '₦ 300,000', '₦ 900,000', '₦ 1,500,000',
       '₦ 1,800,000', '₦ 850,000', '₦ 170,000', '₦ 1,600,000',
       '₦ 650,000', '₦ 750,000', '₦ 1,300,000', '₦ 1,100,000',
       '₦ 2,300,000', '₦ 250,000', '₦ 1,400,000', '₦ 450,000',
       '₦ 200,000', '₦ 120,000', '₦ 1,700,000', '₦ 950,000', '₦ 55,000',
       '₦ 130,000', '₦ 1,900,000', '₦ 65,000', '₦ 1,850,000', '₦ 150,000',
       '₦ 1,650,000', '₦ 470,000', '₦ 1,350,000', '₦ 270,000', '₦ 35,000',
       '₦ 2,200,000', '₦ 2,250,000', '₦ 70,000', '₦ 2,100,000',
       '₦ 840,000', '₦ 210,000', '₦ 216,000', '₦ 250', '₦ 84,000',
       '₦ 160,000', '₦ 1,025,000', '₦ 230,000', '₦ 280,000', '₦ 480,000',
       '₦ 430,000', '₦ 220,000', '₦ 2,400,000', '₦ 330,000', '₦ 180,000',
       '₦ 530,000', '₦ 10,000', '₦ 380,000', '₦ 420,000', '₦ 90,000',
       '₦ 110,000', '₦ 500', '₦ 1,150,000', '₦ 140,000', '₦ 1,250,000',
       '₦ 25,000', '₦ 100,000', '₦ 96,000', '₦ 40,000', '₦ 45,000',
       '₦ 460,000', '₦ 630,000', '₦ 72,000', '₦ 370,000', '₦ 6',
       '₦ 620,000', '₦ 1,200,009', '₦ 50,000', '₦ 320,000', '₦ 1,750,000',
       '₦ 60,000', '₦ 270', '₦ 150', '₦ 350', '₦ 190,000', '₦ 520,000',
       '₦ 1,380,000', '₦ 1,450,000', '₦ 600', '₦ 1', '₦ 750,009',
       '₦ 360,000', '₦ 4,000', '₦ 1,050,000', '₦ 830,000', '₦ 1,620,000',
       '₦ 2,700,000', '₦ 3,000,000', '₦ 3,500,000', '₦ 3,200,000',
       '₦ 2,800,000', '₦ 2,900,000', '₦ 4,000,000', '₦ 3,400,000',
       '₦ 2,850,000', '₦ 3,800,000', '₦ 2,600,000', '₦ 1,300',
       '₦ 2,750,000', '₦ 260,000', '₦ 3,300,000', '₦ 3,625,000',
       '₦ 297,000', '₦ 126,000', '₦ 240,000', '₦ 80,000', '₦ 478,000',
       '₦ 275,000', '₦ 820,000', '₦ 75,009', '₦ 153,000', '₦ 720,000'],
      dtype=object)

No dollar-priced apartments anymore!

In [107]:
data.price = data.price.str.replace(',', '').apply(lambda x: x[2:])

data.price.unique()

array(['2500000', '800000', '1200000', '1000000', '350000', '550000',
       '700000', '2000000', '500000', '400000', '600000', '300000',
       '900000', '1500000', '1800000', '850000', '170000', '1600000',
       '650000', '750000', '1300000', '1100000', '2300000', '250000',
       '1400000', '450000', '200000', '120000', '1700000', '950000',
       '55000', '130000', '1900000', '65000', '1850000', '150000',
       '1650000', '470000', '1350000', '270000', '35000', '2200000',
       '2250000', '70000', '2100000', '840000', '210000', '216000', '250',
       '84000', '160000', '1025000', '230000', '280000', '480000',
       '430000', '220000', '2400000', '330000', '180000', '530000',
       '10000', '380000', '420000', '90000', '110000', '500', '1150000',
       '140000', '1250000', '25000', '100000', '96000', '40000', '45000',
       '460000', '630000', '72000', '370000', '6', '620000', '1200009',
       '50000', '320000', '1750000', '60000', '270', '150', '350',
       '190000', '520000', '1380000', '1450000', '600', '1', '750009',
       '360000', '4000', '1050000', '830000', '1620000', '2700000',
       '3000000', '3500000', '3200000', '2800000', '2900000', '4000000',
       '3400000', '2850000', '3800000', '2600000', '1300', '2750000',
       '260000', '3300000', '3625000', '297000', '126000', '240000',
       '80000', '478000', '275000', '820000', '75009', '153000', '720000'],
      dtype=object)

There are instances where the price value is less than 4 digits. Having a closer look;

In [108]:
cheap_apartments = data[data.price.str.len() <= 5]
cheap_apartments

,neighborhood,price,beds,baths,toilets,extra
city_id,,,,,,
lagos_178,Lekki Phase 1 Lekki Lagos,55000,3 beds,4 baths,4 Toilets,Furnished Serviced Newly BuiltThis is a shorle...
lagos_204,...Abule Oja Yaba Lagos,65000,1 beds,1 baths,1 Toilets,ServicedSERVICED & SPACIOUS ROOMSELF FOR RENT....
lagos_397,Shonibare Estate Mobolaji Bank Anthony Way Ike...,35000,1 beds,1 baths,2 Toilets,Furnished ServicedThe property is one bedroom ...
lagos_430,Parkview Estate Ikoyi Lagos,70000,3 beds,3 baths,4 Toilets,Furnished3 bedroom Flat / Apartment for rent P...
lagos_802,Madonna Estate ojodu Abiodun road Berger Ojodu...,250,1 beds,1 baths,1 Toilets,FurnishedA room self contain for rent at madon...
lagos_820,"Unity street,unity bus stopIgbogbo Ikorodu Lagos",84000,1 beds,1 baths,1 Toilets,"Annual rent:-84,000 A&C:-40,000 Total package:..."
lagos_1344,Akoka Yaba Lagos,10000,beds,baths,Toilets,HOT SHORT-LET ?????? serviced Studio Apartment...
lagos_1696,Itele ogun state close to ayobo LagosAyobo Ipa...,90000,1 beds,1 baths,1 Toilets,newly spacious renovated mini flat all tiles f...
lagos_1753,Ojodu Berger Ojodu Lagos,500,3 beds,3 baths,2 Toilets,????*Just Inn* Standard miniflat with 2 toilet...
lagos_1866,Phase 2 Gbagada Lagos,25000,1 beds,1 baths,1 Toilets,FurnishedAvailable for shortlets @ Gbagada Pha...
lagos_2071,Nasfat street before Agunfoye sawmill along ig...,96000,1 beds,1 baths,1 Toilets,"Annual rent:-96,000 A&C:-50,000 Total package:..."
lagos_2136,Off freedom road lekki phase 1Lekki Phase 1 Le...,40000,1 beds,1 baths,2 Toilets,Furnished Newly Built1 bedroom mini flat Mini ...
lagos_2213,"Off studio 24, Lekki phase 1 Lekki Phase 1 Lek...",45000,2 beds,1 baths,2 Toilets,Spacious serviced 1bedroom flat fully furnishe...
lagos_2346,Itele Ogun state close to Ayobo LagosAyobo Ipa...,90000,1 beds,1 baths,2 Toilets,Renovated mini flat all tiles floor fenced gat...
lagos_2363,Itele Ogun State close to Ayobo LagosAyobo Ipa...,72000,1 beds,1 baths,1 Toilets,Cheap mini flat in a very decent area at ogun ...
lagos_2493,Rumens Road IkoyiOld Ikoyi Ikoyi Lagos,6,1 beds,2 baths,2 Toilets,Furnished Serviced Newly BuiltTo Let Newly bui...
lagos_2502,Igbogbo Ikorodu Lagos,90000,1 beds,1 baths,1 Toilets,"Annual rent:-90,000 A&C:-40,000 Total package:..."
lagos_2543,Off Lekki Epe Expressway Ajah Lagos,70000,2 beds,2 baths,3 Toilets,"Newly BuiltBrand new 2Bedroom Flat, Lekki Epe ..."
lagos_2615,Very decent and beautiful new house 2bedroom a...,50000,2 beds,2 baths,2 Toilets,Furnished Newly BuiltVery decent and beautiful...
lagos_2653,Itele Ogun State close to Ayobo LagosAyobo Ipa...,90000,1 beds,1 baths,1 Toilets,Mini Flat all tiles floor fenced gate water at...
lagos_2697,Spar roadIkate Lekki Lagos,45000,1 beds,1 baths,2 Toilets,Furnished Serviced Newly BuiltBeautifully exec...
lagos_2839,Asekun street off adekunle kuyeAdelabu Suruler...,500,1 beds,1 baths,1 Toilets,Very lovely and place tastefully finished all ...
lagos_3112,Off Admirathy road Lekki phase 1 Lekki Phase 1...,25000,1 beds,1 baths,1 Toilets,Serviced1 bedroom mini flat Studio Apartment F...
lagos_3143,Itele ayobo roadAyobo Ipaja Lagos,60000,1 beds,1 baths,1 Toilets,Newly BuiltSuperb room self contain all ties f...
lagos_3194,Itele Ogun State close to Ayobo LagosAyobo Ipa...,72000,1 beds,1 baths,1 Toilets,Neat Mini flat in a decent area it has water a...
lagos_3208,Okotie Eboh street off Awolowo road ikoyiAwolo...,40000,1 beds,1 baths,2 Toilets,Furnished Serviced Newly Built1 bedroom mini f...
lagos_3222,College road Ifako Ogba Ogba Lagos,270,beds,baths,Toilets,Lovely room self contain for rent at Aguda ogb...
lagos_3225,3 Greenville estate badoreBadore Ajah Lagos,150,1 beds,1 baths,1 Toilets,Furnished Newly BuiltThis is a very neat 2 bed...
lagos_3241,Abule-ijesha road Abule Ijesha Yaba Lagos,350,beds,baths,Toilets,Newly BuiltNewly build ..
lagos_3320,Lekki Phase 1 Lekki Lagos,50000,3 beds,3 baths,4 Toilets,"Newly BuiltFor more information, pricing and p..."
lagos_4221,Commissioner streetIlasan Lekki Lagos,600,1 beds,1 baths,1 Toilets,ServicedA newly renovated room self contain Re...
lagos_4334,Ifako GbagadaIfako Gbagada Gbagada Lagos,1,3 beds,3 baths,3 Toilets,Furnished ServicedLovely 3bedroom flat with al...
lagos_4510,TransformerOkun Ajah Ajah Lagos,4000,1 beds,1 baths,1 Toilets,FurnishedRenovated room and palour self contai...
abuja_295,GwarinpaGwarinpa Abuja,1300,1 beds,1 baths,2 Toilets,"Pop,very beautiful compoud,2toilet rent 1.3m.."
abuja_495,"BY TIMBER SHADE, BWARI, Central Area Abuja",90000,1 beds,0 baths,0 Toilets,"A fenced, gated and metered spacious selfconta..."
abuja_631,...Lugbe Abuja,600,1 beds,2 baths,2 Toilets,Newly BuiltNewly built one bedroom for rent in...
abuja_688,Wuse Zone 7 Harper StreetWuse 2 Abuja,90000,6 beds,2 baths,2 Toilets,Furnished Serviced Newly BuiltA well furnished...
oyo_304,Ibadan Oyo,80000,1 beds,1 baths,1 Toilets,"FurnishedA Room self contain at Ojurin Akobo, ..."
oyo_449,U.i-Ojoo old bank road expressway IbadanIbadan...,80000,1 beds,1 baths,1 Toilets,Furnished ServicedHostel apartments suitable ...
oyo_462,Alawaye street off akanran roadIwo Rd Ibadan Oyo,75009,1 beds,1 baths,1 Toilets,Serviced Newly BuiltNewly built compact 1 bedr...
oyo_501,Alakia old ife road inside airport second gate...,60000,1 beds,1 baths,1 Toilets,FurnishedA standard neat Room self contain wit...
ogun_18,Itele ogun state close to ayobo LagosAyobo Ipa...,90000,1 beds,1 baths,1 Toilets,newly spacious renovated mini flat all tiles f...
ogun_31,Itele Ogun state close to Ayobo LagosAyobo Ipa...,90000,1 beds,1 baths,2 Toilets,Renovated mini flat all tiles floor fenced gat...
ogun_32,Itele Ogun State close to Ayobo LagosAyobo Ipa...,72000,1 beds,1 baths,1 Toilets,Cheap mini flat in a very decent area at ogun ...
ogun_36,Itele Ogun State close to Ayobo LagosAyobo Ipa...,90000,1 beds,1 baths,1 Toilets,Mini Flat all tiles floor fenced gate water at...
ogun_47,Itele Ogun State close to Ayobo LagosAyobo Ipa...,72000,1 beds,1 baths,1 Toilets,Neat Mini flat in a decent area it has water a...
rivers_94,"Golf Estate, end of Peter Odili RoadTrans Amad...",35000,2 beds,2 baths,2 Toilets,Furnished ServicedA tastefully furnished 2 Bed...

While the apartments in Ogun and Rivers might be truly cheap, those in Lagos and Abuja might be due to data inconsistencies.

In [109]:
exempted_towns = ['korodu', 'ogun', 'Ayobo', 'Ibadan']
for town in exempted_towns:
    cheap_apartments = cheap_apartments[~cheap_apartments.neighborhood.str.contains(town)]
cheap_apartments

,neighborhood,price,beds,baths,toilets,extra
city_id,,,,,,
lagos_178,Lekki Phase 1 Lekki Lagos,55000,3 beds,4 baths,4 Toilets,Furnished Serviced Newly BuiltThis is a shorle...
lagos_204,...Abule Oja Yaba Lagos,65000,1 beds,1 baths,1 Toilets,ServicedSERVICED & SPACIOUS ROOMSELF FOR RENT....
lagos_397,Shonibare Estate Mobolaji Bank Anthony Way Ike...,35000,1 beds,1 baths,2 Toilets,Furnished ServicedThe property is one bedroom ...
lagos_430,Parkview Estate Ikoyi Lagos,70000,3 beds,3 baths,4 Toilets,Furnished3 bedroom Flat / Apartment for rent P...
lagos_802,Madonna Estate ojodu Abiodun road Berger Ojodu...,250,1 beds,1 baths,1 Toilets,FurnishedA room self contain for rent at madon...
lagos_1344,Akoka Yaba Lagos,10000,beds,baths,Toilets,HOT SHORT-LET ?????? serviced Studio Apartment...
lagos_1753,Ojodu Berger Ojodu Lagos,500,3 beds,3 baths,2 Toilets,????*Just Inn* Standard miniflat with 2 toilet...
lagos_1866,Phase 2 Gbagada Lagos,25000,1 beds,1 baths,1 Toilets,FurnishedAvailable for shortlets @ Gbagada Pha...
lagos_2136,Off freedom road lekki phase 1Lekki Phase 1 Le...,40000,1 beds,1 baths,2 Toilets,Furnished Newly Built1 bedroom mini flat Mini ...
lagos_2213,"Off studio 24, Lekki phase 1 Lekki Phase 1 Lek...",45000,2 beds,1 baths,2 Toilets,Spacious serviced 1bedroom flat fully furnishe...
lagos_2493,Rumens Road IkoyiOld Ikoyi Ikoyi Lagos,6,1 beds,2 baths,2 Toilets,Furnished Serviced Newly BuiltTo Let Newly bui...
lagos_2543,Off Lekki Epe Expressway Ajah Lagos,70000,2 beds,2 baths,3 Toilets,"Newly BuiltBrand new 2Bedroom Flat, Lekki Epe ..."
lagos_2615,Very decent and beautiful new house 2bedroom a...,50000,2 beds,2 baths,2 Toilets,Furnished Newly BuiltVery decent and beautiful...
lagos_2697,Spar roadIkate Lekki Lagos,45000,1 beds,1 baths,2 Toilets,Furnished Serviced Newly BuiltBeautifully exec...
lagos_2839,Asekun street off adekunle kuyeAdelabu Suruler...,500,1 beds,1 baths,1 Toilets,Very lovely and place tastefully finished all ...
lagos_3112,Off Admirathy road Lekki phase 1 Lekki Phase 1...,25000,1 beds,1 baths,1 Toilets,Serviced1 bedroom mini flat Studio Apartment F...
lagos_3208,Okotie Eboh street off Awolowo road ikoyiAwolo...,40000,1 beds,1 baths,2 Toilets,Furnished Serviced Newly Built1 bedroom mini f...
lagos_3222,College road Ifako Ogba Ogba Lagos,270,beds,baths,Toilets,Lovely room self contain for rent at Aguda ogb...
lagos_3225,3 Greenville estate badoreBadore Ajah Lagos,150,1 beds,1 baths,1 Toilets,Furnished Newly BuiltThis is a very neat 2 bed...
lagos_3241,Abule-ijesha road Abule Ijesha Yaba Lagos,350,beds,baths,Toilets,Newly BuiltNewly build ..
lagos_3320,Lekki Phase 1 Lekki Lagos,50000,3 beds,3 baths,4 Toilets,"Newly BuiltFor more information, pricing and p..."
lagos_4221,Commissioner streetIlasan Lekki Lagos,600,1 beds,1 baths,1 Toilets,ServicedA newly renovated room self contain Re...
lagos_4334,Ifako GbagadaIfako Gbagada Gbagada Lagos,1,3 beds,3 baths,3 Toilets,Furnished ServicedLovely 3bedroom flat with al...
lagos_4510,TransformerOkun Ajah Ajah Lagos,4000,1 beds,1 baths,1 Toilets,FurnishedRenovated room and palour self contai...
abuja_295,GwarinpaGwarinpa Abuja,1300,1 beds,1 baths,2 Toilets,"Pop,very beautiful compoud,2toilet rent 1.3m.."
abuja_495,"BY TIMBER SHADE, BWARI, Central Area Abuja",90000,1 beds,0 baths,0 Toilets,"A fenced, gated and metered spacious selfconta..."
abuja_631,...Lugbe Abuja,600,1 beds,2 baths,2 Toilets,Newly BuiltNewly built one bedroom for rent in...
abuja_688,Wuse Zone 7 Harper StreetWuse 2 Abuja,90000,6 beds,2 baths,2 Toilets,Furnished Serviced Newly BuiltA well furnished...
rivers_94,"Golf Estate, end of Peter Odili RoadTrans Amad...",35000,2 beds,2 baths,2 Toilets,Furnished ServicedA tastefully furnished 2 Bed...

Now we can drop the truly ridiculous ones;

In [110]:
data.drop(cheap_apartments.index, inplace=True)
data.head()

,neighborhood,price,beds,baths,toilets,extra
city_id,,,,,,
lagos_0,OLALEYE Estate Alaka Iponri Surulere Lagos,2500000,3 beds,4 baths,4 Toilets,Brand new service 3 bedroom flat all rooms ens...
lagos_1,"Off Kudirat Abiola way, Julie EstateOregun Ike...",2500000,3 beds,3 baths,4 Toilets,The property is a 3 Bedrooms Upscale FLAT all ...
lagos_3,...Lekki Phase 1 Lekki Lagos,800000,1 beds,1 baths,1 Toilets,"For more information, Pricing, and Private Vie..."
lagos_4,Lekki Phase 1 Lekki Lagos,1200000,1 beds,1 baths,1 Toilets,"For more information, Pricing, and Private Vie..."
lagos_5,Ketu Lagos,1000000,2 beds,2 baths,2 Toilets,Brand new 2 bedrooms flat for rent at Ketu Lag...

### Cleaning Beds, Baths, Toilets;

In [111]:
data.beds.unique()

array(['3 beds', '1 beds', '2 beds', 'beds', '4 beds', '0 beds', '5 beds',
       '6 beds', '3 beds ', '10 beds', 'beds ', '8 beds'], dtype=object)

Some beds don't have a digit value, while some have 0.

In [112]:
no_beds = data[data.beds.str.startswith('beds')]
no_beds

,neighborhood,price,beds,baths,toilets,extra
city_id,,,,,,
lagos_7,Salem LekkiIkate Lekki Lagos,1000000,beds,baths,Toilets,Nice and Standard Renovated Mini Flat availabl...
lagos_12,Akinola Akoka Yaba Lagos,400000,beds,baths,1 Toilets,Furnished ServicedThis is a lovely SelfContain...
lagos_17,St.Finbars Akoka Yaba Lagos,500000,beds,baths,1 Toilets,Furnished Serviced Newly BuiltThis is a lovely...
lagos_18,St. Finbars Akoka Yaba Lagos,600000,beds,baths,1 Toilets,Furnished Serviced Newly BuiltThis is a lovely...
lagos_31,Lawanson Surulere Lagos,300000,beds,baths,Toilets,*Clean Miniflat with tiles and water at idiara...
...,...,...,...,...,...,...
rivers_84,Trans Amadi Port Harcourt Rivers,550000,beds,baths,Toilets,Cool 2 Bedroom Flat For Rent in Woji Port Harc...
rivers_85,Trans Amadi Port Harcourt Rivers,600000,beds,baths,Toilets,Modern King Size 2 Bedroom Flat For Rent In Wo...
rivers_86,Trans Amadi Port Harcourt Rivers,800000,beds,baths,Toilets,Tastefully Finished 2 Bedroom Flat For Rent in...
rivers_88,Eliozu Port Harcourt Rivers,800000,beds,baths,Toilets,Well Finished Brand new 2 Bedroom Flat For Ren...
rivers_90,Trans Amadi Port Harcourt Rivers,400000,beds,baths,Toilets,Decent Size 2 Bedroom Flat For Rent In Woji Po...

In [113]:
data.drop(no_beds.index, inplace=True)

data.beds.unique()

array(['3 beds', '1 beds', '2 beds', '4 beds', '0 beds', '5 beds',
       '6 beds', '3 beds ', '10 beds', '8 beds'], dtype=object)

In [114]:
data.beds = data.beds.map(lambda x: x[0]).astype(int)

data.beds.unique()

array([3, 1, 2, 4, 0, 5, 6, 8])

Great! Now onto the 0 beds;

In [115]:
data[data.beds == 0]

,neighborhood,price,beds,baths,toilets,extra
city_id,,,,,,
lagos_65,"Close to 3rd Mainland Bridge, Yaba, Lagos. Yab...",800000,0,0 baths,0 Toilets,Currently Being Renovated: Spacious Miniflat (...
lagos_212,...Adeniyi Jones Ikeja Lagos,2000000,0,2 baths,3 Toilets,JUST OUT IN ADENIYI JONES 2 bedroom Luxery apa...
lagos_254,Chemist Akoka Yaba Lagos,400000,0,0 baths,1 Toilets,ServicedThis is a lovely SelfContain @ Akoka Y...
lagos_268,Obadia- off ilaje roadBariga Shomolu Lagos,350000,0,0 baths,0 Toilets,FurnishedA Newly Renovated Mini Flat @ Obadiah...
lagos_441,destiny home estate Abijo AJAHAbijo Ajah Lagos,500000,0,0 baths,0 Toilets,Room and parlour self contain for rent at dest...
...,...,...,...,...,...,...
rivers_61,...Trans Amadi Port Harcourt Rivers,800000,0,0 baths,0 Toilets,Modern King Size 3 Bedroom Flat For Rent In Wo...
rivers_75,- Trans Amadi Port Harcourt Rivers,750000,0,0 baths,0 Toilets,Beautiful 1 Bedroom Flat For Rent In Woji Port...
rivers_82,...Trans Amadi Port Harcourt Rivers,500000,0,0 baths,0 Toilets,Neat 2 Bedroom Flat For Rent in Woji Port Harc...
rivers_83,- Trans Amadi Port Harcourt Rivers,1000000,0,0 baths,0 Toilets,Decent king size 2 Bedroom Flat For Rent In Pe...
rivers_89,-Trans Amadi Port Harcourt Rivers,1200000,0,0 baths,0 Toilets,Decent 2 Bedroom Flat For Rent in Peter Odili ...

Some of them are just plain errors and are already in the description column.

In [118]:
for i in range(1, 6):
    data.loc[data.extra.str.contains(str(i)), 'beds'] = i
data.loc[data.extra.str.contains('two'), 'beds'] = 2 # for those written in words
data.loc[data.extra.str.contains('three'), 'beds'] = 3 # for those written in words

data.loc[data.extra.str.contains('and parlour'), 'beds'] = 1 # for 'room and parlour' apartments
data.loc[data.extra.str.contains('elf'), 'beds'] = 1 # for 'self contained' apartments

bed_zero = data[data.beds == 0]
bed_zero

,neighborhood,price,beds,baths,toilets,extra
city_id,,,,,,
lagos_467,...Ilasan Lekki Lagos,1000000,0,0 baths,0 Toilets,JUST OUT!! SEMI DIRECT!! VERY CLEAN MINI FLAT ...
lagos_500,Harmony estateAjah Lagos,400000,0,0 baths,0 Toilets,Very spacious and neat environment..
lagos_656,Nice and Secure EstateChevron Lekki Lagos,1500000,0,0 baths,0 Toilets,ServicedNice and Standard Mini Flat with inten...
lagos_1683,"Abule oja, second gate, yaba-lagos..Abule Oja ...",400000,0,0 baths,0 Toilets,FurnishedVery specious and standard mini flat ...
lagos_1706,Green Field EstateAgo Palace Okota Lagos,700000,0,0 baths,0 Toilets,Newly built Executive Lovely Sharp Mini Flat o...
lagos_1980,Arowojobe EstateMende Maryland Lagos,1000000,0,0 baths,0 Toilets,Brand new Tastefully finished miniflat with en...
lagos_2118,Bama villaAbule Ijesha Yaba Lagos,400000,0,1 baths,1 Toilets,FurnishedHOT LETTING: Lovely built serviced ap...
lagos_2310,SomodiShomolu Shomolu Lagos,500000,0,0 baths,0 Toilets,Mini flat Flat / Apartment for rent Somodi Sho...
lagos_2624,"Idaosa ojo osagie, off peace estate AgudaAguda...",700000,0,0 baths,0 Toilets,"FurnishedTOLET A Tastefully finished,spacious ..."
lagos_2849,...Ago Palace Okota Lagos,450000,0,0 baths,0 Toilets,FurnishedStandard Mini Flat on a good Environm...
lagos_2902,...Ikeja Gra Ikeja Lagos,2000000,0,0 baths,0 Toilets,"Brand new, exquisitely finished and fully furn..."
lagos_3343,Amule bus stop AyoboAyobo Ipaja Lagos,200000,0,0 baths,0 Toilets,A newly built mini flat at the back of access ...
lagos_3387,"nnobi street,kilo, surulere,LagosSurulere Lagos",650000,0,0 baths,0 Toilets,For lease: Fully finished mini flat with wardr...
lagos_3455,"BOGIJE, ELEMOROAjah Lagos",350000,0,0 baths,0 Toilets,"Tastefully finished POP mini flat, spacious, w..."
lagos_3985,AlapereKetu Lagos,450000,0,0 baths,0 Toilets,"Newly BuiltNewly built pop finished , spacious..."
lagos_4053,ShopRite Road Osapa London LekkiOsapa London L...,350000,0,0 baths,0 Toilets,Serviced Newly BuiltNice and Standard Newly Bu...
lagos_4250,"S Forte Estate, Before BlencoAdo Ajah Lagos",650000,0,0 baths,0 Toilets,"Flat / Apartment for rent S Forte Estate, Befo..."
lagos_4325,Iju ishagaIfako Ogba Ogba Lagos,300000,0,0 baths,0 Toilets,*BRAND NEW EXECUTIVE MINI FLAT AT IJU ISHAGA* ...
lagos_4473,...Ebute Metta Yaba Lagos,350000,0,0 baths,0 Toilets,VERY SPACIOUS & DECENT NEWLY RENOVATED ROOM SE...
oyo_431,First Power line Eleyele/OloguneruIbadan Oyo,150000,0,0 baths,0 Toilets,It is located in a well conducive and serene e...
oyo_433,Old BodijaBodija Ibadan Oyo,400000,0,0 baths,0 Toilets,It is located in a well conducive and serene e...

And I've reduced 161 unknown rooms to just a handful!

In [120]:
data.drop(bed_zero.index, inplace=True)

data.beds.unique()

array([3, 1, 2, 5, 4])

**Moving on to Baths;**

In [121]:
data.baths.unique()

array(['4 baths', '3 baths', '1 baths', '2 baths', ' baths', '0 baths',
       ' 2 baths', '5 baths', ' 3 baths', ' 1 baths', '  baths',
       '6 baths', '10 baths', ' 5 baths'], dtype=object)

In [122]:
data.baths = data.baths.str.strip()

data.baths.unique()

array(['4 baths', '3 baths', '1 baths', '2 baths', 'baths', '0 baths',
       '5 baths', '6 baths', '10 baths'], dtype=object)

In [124]:
no_baths = data[data.baths.str.startswith('baths')]
no_baths

,neighborhood,price,beds,baths,toilets,extra
city_id,,,,,,
lagos_26,Agege Lagos,800000,3,baths,Toilets,"Brand new 3 bedroom flat in Oko Oba, Agege for..."
lagos_28,Off Demurin road Ketu Kosofe Ikosi Lagos,400000,1,baths,Toilets,Newly renovated upstairs roomself apartment pr...
lagos_29,Off Demurin road Ketu Kosofe Ikosi Lagos,1000000,2,baths,Toilets,"Newly renovated 2 bedrooms flats with dining, ..."
lagos_30,Seaside estate badoreBadore Ajah Lagos,1800000,4,baths,Toilets,"4bedroom duplex, alone in the compound, pop fi..."
lagos_68,"Alagomeji-Adekunle, Close to the 3rd Mainland ...",1500000,2,baths,2 Toilets,Lovely New & Very Spacious Executive 2 Bedroom...
...,...,...,...,...,...,...
ogun_108,Obafemi Owode Ogun,400000,2,baths,Toilets,FurnishedA Nice 2 Bedroom Apartment in a Priva...
ogun_153,Arepo private EstateArepo Arepo Ogun,500000,2,baths,3 Toilets,Furnished Newly BuiltLovely 2 bed room flat at...
ogun_182,Agbeloba upright hotel street Abalawa Abeokuta...,250000,1,baths,1 Toilets,Newly BuiltRoom and parlour self contained wit...
rivers_81,Trans Amadi Port Harcourt Rivers,400000,1,baths,Toilets,Tastefully Finished New 1 Bedroom Flat For Ren...
rivers_87,Eliozu Port Harcourt Rivers,1000000,2,baths,Toilets,Decent Brand new 2 Bedroom Flat For Rent In Sh...

**Dealing with Toilets;**

In [125]:
data.toilets.unique()

array(['4 Toilets', '1 Toilets', '2 Toilets', '3 Toilets', ' Toilets',
       ' 4 Toilets', '0 Toilets', ' 1 Toilets', '5 Toilets', ' 0 Toilets',
       '6 Toilets', ' 3 Toilets', ' 2 Toilets', '10 Toilets', '  Toilets'],
      dtype=object)

In [126]:
data.toilets = data.toilets.str.strip()

data.toilets.unique()

array(['4 Toilets', '1 Toilets', '2 Toilets', '3 Toilets', 'Toilets',
       '0 Toilets', '5 Toilets', '6 Toilets', '10 Toilets'], dtype=object)

In [128]:
data[data.toilets.str.startswith('T')]

,neighborhood,price,beds,baths,toilets,extra
city_id,,,,,,
lagos_26,Agege Lagos,800000,3,baths,Toilets,"Brand new 3 bedroom flat in Oko Oba, Agege for..."
lagos_28,Off Demurin road Ketu Kosofe Ikosi Lagos,400000,1,baths,Toilets,Newly renovated upstairs roomself apartment pr...
lagos_29,Off Demurin road Ketu Kosofe Ikosi Lagos,1000000,2,baths,Toilets,"Newly renovated 2 bedrooms flats with dining, ..."
lagos_30,Seaside estate badoreBadore Ajah Lagos,1800000,4,baths,Toilets,"4bedroom duplex, alone in the compound, pop fi..."
lagos_161,Masha Surulere Lagos,1600000,3,2 baths,Toilets,ServicedFOR RENT... A SERVICED & EXECUTIVE 3BE...
...,...,...,...,...,...,...
rivers_70,Trans Amadi Port Harcourt Rivers,1100000,3,3 baths,Toilets,Spacious 3 Bedroom Flat For Rent in Peter Odil...
rivers_72,-Trans Amadi Port Harcourt Rivers,1500000,3,3 baths,Toilets,Tastefully Built 3 Bedroom Flat For Rent in Pe...
rivers_76,Trans Amadi Port Harcourt Rivers,1000000,3,3 baths,Toilets,Executive Newly Built 3 Bedroom Flat For Rent ...
rivers_81,Trans Amadi Port Harcourt Rivers,400000,1,baths,Toilets,Tastefully Finished New 1 Bedroom Flat For Ren...
rivers_87,Eliozu Port Harcourt Rivers,1000000,2,baths,Toilets,Decent Brand new 2 Bedroom Flat For Rent In Sh...